### ISSUE TITLE
工具已经失效.

### ISSUE THREAD

**Issue by by-justin** [nemoTyrant/goose#1]
下载诸如 https://pri-cdn-tx.xiaoeknow.com/appxV6ykvAO1421/private_index/1670897709nYgHfQ.m3u8?sign=f694ac****f2&t=63**06 报链接无效, 下载本地 m3u8 报 download error 8

**Comment by nemoTyrant** [comment]
@justin-himself 不好意思，我已经很久没有用过小鹅通了，目前也没有精力查这个问题，请自行研究吧

**Comment by nemoTyrant** [comment]
@justin-himself 已经有靓仔提pr了，可以拉最新代码试一下好了没有
